---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: secrets-manager
spec:
  interval: 30m
  url: https://1password.github.io/connect-helm-charts/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
  namespace: secrets-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: secrets-manager
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      create: true
      watchNamespace:
        - "default"
        - "flux-system"
        - "secrets-manager"
