---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      create: true
      autoRestart: true
      watchNamespace:
        - "default"
        - "flux-system"
        - "secrets-manager"
        - "home-automation"
        - "cert-manager"
