apiVersion: v1
kind: Service
metadata:
  name: home-assistant-codeserver
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 12321
      targetPort: codeserver
  clusterIP: ${CLUSTER_LB_HASS_CS}
  type: LoadBalancer
