---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: hass-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: hass.p4rkh4us.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
  tls:
    - secretName: hass-p4rkh4us-com-tls
      hosts:
        - hass.p4rkh4us.com
