---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      # version: 3.0.1 # for bitnami
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "${METALLB_LB_RANGE}"

    controller:
      image:
        repository: quay.io/metallb/controller
        tag: v0.12

    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: v0.12
