apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant2
spec:
  ports:
    - name: hass
      port: 8123
      targetPort: hass
    - name: http
      port: 85
      targetPort: 80
  selector:
    app: homeassistant
  type: NodePort
