---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass-config-github-runner
  labels:
    app: hass-config-github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hass-config-github-runner
  template:
    metadata:
      labels:
        app: hass-config-github-runner
    spec:
      containers:
        - name: github-runner
          image: myoung34/github-runner:2.319.1
          env:
            - name: RUNNER_NAME
              value: hass-config-runner
            - name: REPO_URL
              value: https://github.com/carsten-bo/homeassistant-config
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner-secrets
                  key: personal-access-token
          volumeMounts:
            - mountPath: /hass-volume
              name: hass-volume

          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "mkdir -p $HOME/.ssh"]

          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"

      volumes:
        - name: hass-volume
          persistentVolumeClaim:
            claimName: hass-rwm-longhorn-pvc
