---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deconz-deployment
  labels:
    app: deconz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deconz
  template:
    metadata:
      labels:
        app: deconz
    spec:
      restartPolicy: Always
      containers:
        - name: deconz
          image: deconzcommunity/deconz:stable
          ports:
            - containerPort: 80
              name: deconz
          env:
            - name: DECONZ_WEB_PORT
              value: "80"
            - name: DECONZ_WS_PORT
              value: "443"
            - name: DECONZ_UPNP
              value: "0"
            - name: TZ
              value: "Europe/Berlin"
            - name: DECONZ_DEVICE
              value: "/dev/ttyACM0"
          volumeMounts:
            - name: deconz-volume
              mountPath: /opt/deCONZ
            - name: ttyacm
              mountPath: /dev/ttyACM0
          securityContext:
            privileged: true

      volumes:
        - name: deconz-volume
          persistentVolumeClaim:
            claimName: deconz-local-path-claim
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
            type: CharDevice
