---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deconz
spec:
  interval: 5m
  chart:
    spec:
      chart: deconz
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: deconzcommunity/deconz
      tag: 2.15.02

    env:
      TZ: "Europe/Berlin"
      DECONZ_WEB_PORT: 81
      DECONZ_WS_PORT: 445
      DECONZ_DEVICE: "/dev/ttyACM0"
      DECONZ_VNC_MODE: 1
      DECONZ_VNC_PORT: 5900
      DECONZ_VNC_PASSWORD:
        secretKeyRef:
          name: deconz-secrets
          key: vnc-password

    service:
      main:
        ports:
          http:
            port: 81
          websocket:
            enabled: true
            port: 445
          vnc:
            enabled: true
            port: 5900

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: deconz-longhorn-pvc
        mountPath: /opt/deCONZ
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2429387-if00
        hostPathType: CharDevice
        mountPath: /dev/ttyACM0

    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true

    securityContext:
      privileged: true

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/conbee
                  operator: In
                  values:
                    - "true"
