---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deconz
spec:
  interval: 5m
  chart:
    spec:
      chart: deconz
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: deconzcommunity/deconz
      tag: 2.15.01

    env:
      TZ: "Europe/Berlin"
      DECONZ_WEB_PORT: 80
      DECONZ_WS_PORT: 443
      DECONZ_DEVICE: "/dev/ttyACM0"
      # DECONZ_VNC_MODE: 1

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: deconz-local-path-claim
        mountPath: /opt/deCONZ
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0
        hostPathType: CharDevice
        mountPath: /dev/ttyACM0

    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true

    securityContext:
      privileged: true
