---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: deconz-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: home-automation-deconz-mw@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  name: "http"
          - path: /deconz
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  name: "http"
