---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: deconz-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: deconz.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  number: 81
  tls:
    - secretName: "${SECRET_CERTIFICATE_DEFAULT}"
      hosts:
        - deconz.${SECRET_DOMAIN}
