---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: deconz-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-deconz-mw@kubernetescrd
spec:
  rules:
    - http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: deconz
          #       port:
          #         number: 808
          - path: /deconz
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  number: 808
