---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: deconz-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  name: "http"
          - path: /deconz
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  name: "http"
