---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-local-path-claim
  labels:
    - kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
