---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-local-path-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
