---
apiVersion: v1
kind: Service
metadata:
  name: deconz
  labels:
    app: deconz
spec:
  ports:
    - port: 808
      targetPort: "http"
      name: "http"
  selector:
    app: deconz
  type: ClusterIP
