---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - secrets-manager
  - secret-reflector
  - cert-manager
  - storage-system
  - descheduler
  - metallb-system
  - kube-system
  # - persistence
