---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth

spec:
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        name: traefik-forward-auth
        app: traefik-forward-auth
    spec:
      containers:
        - name: traefik-forward-auth
          # image: thomseddon/traefik-forward-auth:2
          image: ghcr.io/kitos9112/traefik-forward-auth
          tag: v2.6.6
          pullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: trace
            - name: LOG_FORMAT
              value: pretty
            - name: LOGOUT_REDIRECT
              value: "https://www.google.de"
            - name: WHITELIST
              value: ${SECRET_TRAEFIK_AUTH_WHITELIST}
            - name: LIFETIME
              value: "28000"
            - name: URL_PATH
              value: "/_oauth"
            - name: AUTH_HOST
              value: "auth.${SECRET_DOMAIN}"
            - name: COOKIE_DOMAIN
              value: "${SECRET_DOMAIN}"
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              value: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID}"
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              value: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET}"
            - name: SECRET
              value: "${SECRET_TRAEFIK_AUTH}"
            # - name: INSECURE_COOKIE
            #   value: false
          ports:
            - containerPort: 4181
          resources:
            requests:
              cpu: "25m"
              memory: "25Mi"
            limits:
              cpu: "300m"
              memory: "150Mi"
