# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CERTIFICATE_DEFAULT: ENC[AES256_GCM,data:szEeqOyKlI4OMv+o1FgfkO4=,iv:sX/FXKs41FacOOOIqj9XEEc0YHWX+gRykmIjk3Bi7+Y=,tag:1N2j0L/POcnlB4EvGDbdfQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:TJu2/glJCfariBgi,iv:42xs/ydcsFdbkUdUD9yffsfsvGoS06aUDRLVueAMrUs=,tag:gLqvPM3mBG7ioa3gZ9inHw==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:AFhZOEbOSw/Ua3hLL7E=,iv:nhVZ6+SROfUnh+J3PPmb7gSZV5cViOi3DEKmf20N1q4=,tag:4EY/cMxVQtaLc/2Hq3MAjQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:p4hRjgXivlgy6pJPJ0t27xvthN9Goz8=,iv:bGBb0ZMLbj9RdCM5bheIfzMDxq8SyelOi4mibYnYda8=,tag:mRVrCBF/7JprVQ5W/pmQ/w==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:DRPDNvPUz635hgriC/5S9FJGfz0=,iv:ZcfsyL/fLqKR3IKHZDeCUS7MdpIiRwThgRegeKDO3ZQ=,tag:RdBIKCUlPukGPVkhGrxlwg==,type:str]
    CLUSTER_LB_HASS: ENC[AES256_GCM,data:olMZBXL1jlgzB+wHsTgB,iv:EXrYIOqLiFePV/Hvu/qAayvRUCUTR/grodJGdl76VhA=,tag:+kVqt5Ska0TU0dxRt5qjYA==,type:str]
    CLUSTER_LB_HASS_CS: ENC[AES256_GCM,data:GFtvVp3y4M1Pyo9CiDAC,iv:LMdu3f7LUB9tazhWiqmtEmbf8xAGwC7LVrRaHA7BSQs=,tag:OZ7WPAF7zJIwXOEv5bhdSg==,type:str]
    CLUSTER_LB_K8S_DASHBOARD: ENC[AES256_GCM,data:tM1ypOWM2djXu8KoK6FQ,iv:cTLJ5uVvspx1BzTbSGRbUKs8hEKp85Ib7bmfcLIV0HA=,tag:UfKDJATM4gs1wVONtt2keA==,type:str]
    CLUSTER_LB_APPDAEMON: ENC[AES256_GCM,data:CrQFYKLCfV0sxKHPQFhv,iv:A1leXyiSfWnkWrxt5z3nFF0CyWNL3s1nPEQRWe9LsMA=,tag:+FkFMvqD8lceqFxsn+QA/g==,type:str]
    KUBE_VIP_ADDRESS: ENC[AES256_GCM,data:2HkkvDPtTNjoLK1jRTMW,iv:o4o3CnB/tr9DNl5gYxImmvO7zkZeda+C0BGdODDgUeA=,tag:WXWUb4XCCLATQHUix+Hq2w==,type:str]
    KUBE_VIP_INTERFACE: ENC[AES256_GCM,data:Ur0DTw==,iv:fsI3Bj3JAOC1pgMTKAetv9XvBNNvBzV4MpZDp3BiCDg=,tag:4Y0M3O/w5AajbbMOVyo5Wg==,type:str]
    SECRET_TRAEFIK_AUTH_WHITELIST: ENC[AES256_GCM,data:qSUBiq0wZEpfdKuS3C6LWElLl5jTuWY=,iv:x7SygsdJSKobIYo5Mj67QUF4TfNUrjuh9iXPweJU104=,tag:REO1LsZcsA7aPxuoXQjPuQ==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:oaLu62YbBiFtj7SCa04EhxLUquavWTVmJ758fC1M7ysjogpaWRsHfqKgbi61Q3ZSgazJOZXn9qpup6zNTP+K0dFZPuc7R9sm,iv:dynaeLViKSS7Giq9p4eRWv4B7WC3Cs1VwBATFIIVWN8=,tag:q0S2Wr7KpGU6XzMPmGrXRg==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:hZ9jz3M5aDl2RbCt/7NaR4STB4w5MvrVtdeiRMaT+ds715A=,iv:n3ycoNA4TXybTwSZo1GySev9WIne2ObgvjEBfMHIzqA=,tag:LhXnwKqckoBNJ7V3w6QjXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lclclmh57a3jmt4up3vlqw6glkpau4lwgp0ruasggaqzzuvjh4aqycse0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSjlDMHQ0SndEYmMvZXN2
            NG9mSHlEWEoxckZWbXdOUFRlSDVJbnVUbUhnClprbTJEZTlvWDBTQTIrME5IdzJD
            V2t1TEF0cis2Y2NjSTU4TmV0ODUxQnMKLS0tIDlZczhpaUJGeVlCZVZIenJFam56
            N1RHOFZabjJOdHZvN0t1QWNEd01QS1EKK4U8U4L2LFRt+GgaI86wVkEXkeru3e4U
            z7l22YOx78xyk9l8aCj3uX5tTXbJbCZx6uz5i+/OIVOqd/V+wY2sUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-08T21:34:31Z"
    mac: ENC[AES256_GCM,data:GSu8eHVFNoZtOr+blPKqVapBqzWPQrkXzu34LFzCsJYcJ6md4o9RRbkFHzgENPa8x9XIYRopa+BsP+JW8JQDGmfHOCQu5S1N8ShCu5Aaw6BjALA8jlJ97AkDdH5fiOfaczScHQLj6Ce7Gxw/ebaE2/KDrBFHVloDYpA0UibrYgI=,iv:2c0zKazaud0sM8ZyyT7N2IHMq7TujzG/Wx6+fS+830k=,tag:KpKqg5JrZ05gO0ooBUEWHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
