---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: 0.23.1
      sourceRef:
        kind: HelmRepository
        name: descheduler-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kind: Deployment

    image:
      repository: k8s.gcr.io/descheduler/descheduler
      tag: v0.24.1

    deschedulerPolicy:
      strategies:
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        # RemoveDuplicates:
        #   enabled: true
        # RemovePodsViolatingNodeTaints:
        #   enabled: true
        # RemovePodsViolatingInterPodAntiAffinity:
        #   enabled: true
        # LowNodeUtilization:
        #   enabled: true
        #   params:
        #     nodeResourceUtilizationThresholds:
        #       thresholds:
        #         cpu: 20
        #         memory: 20
        #         pods: 20
        #       targetThresholds:
        #         cpu: 50
        #         memory: 50
        #         pods: 50
