---
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
metadata:
  name: high-node-utilization-policy
strategies:
  "HighNodeUtilization":
    enabled: true
    params:
      nodeResourceUtilizationThresholds:
        thresholds:
          "memory": 20
