---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - helm-release.yaml
  - high-node-utilization.yaml
  - low-node-utilization.yaml
  - node-affinity.yaml
  - failed-pods.yaml
