---
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
metadata:
  name: node-affinity-policy
strategies:
  RemovePodsViolatingNodeAffinity:
    enabled: true
    params:
      nodeAffinityType:
        - "requiredDuringSchedulingIgnoredDuringExecution"
