---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: node-label-monitor
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node-label-monitor
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node-label-monitor
subjects:
  - kind: ServiceAccount
    name: node-label-monitor
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node-label-monitor
  apiGroup: rbac.authorization.k8s.io
