---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: rook-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: rook/ceph
      tag: v1.9.1-18.g9c74e9bb3
