---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-feature-discovery
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: kube-system
      interval: 5m
  values:
    worker:
      config:
        core:
          labelSources:
            - all
          featureSources:
            - all
