---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: nfd-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.11.0
