---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`monitor.${SECRET_DOMAIN}`) && Host(`prometheus.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: appdaemon
          port: 5050
          scheme: http
      middlewares:
        - name: traefik-forward-auth
          namespace: networking
  tls:
    secretName: "${SECRET_CERTIFICATE_DEFAULT}"
