---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdeamon
spec:
  interval: 5m
  chart:
    spec:
      chart: appdaemon
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    env:
      - name: TZ
        value: "Europe/Berlin"
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: appdaemon-local-path-claim
