---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdeamon
spec:
  interval: 5m
  chart:
    spec:
      chart: appdaemon
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: acockburn/appdaemon
      tag: 4.2.1

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${CLUSTER_LB_APPDAEMON}
        externalTrafficPolicy: Local

    env:
      TZ: "Europe/Berlin"
      HA_URL: "http://$(HOME_ASSISTANT_SERVICE_HOST):$(HOME_ASSISTANT_SERVICE_PORT)"
      TOKEN:
        secretKeyRef:
          name: appdaemon-secrets
          key: token
      DASH-URL: "http://$(APPDAEMON_SERVICE_HOST):$(APPDAEMON_SERVICE_PORT)"

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: appdaemon-longhorn-pvc
        mountPath: /conf

    # dnsPolicy: ClusterFirstWithHostNet
    # hostNetwork: true
