---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdeamon
  annotations:
    operator.1password.io/item-path: "vaults/Kubernetes/items/appdaemon"
    operator.1password.io/item-name: "appdaemon-secrets"
spec:
  interval: 5m
  chart:
    spec:
      chart: appdaemon
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: acockburn/appdaemon
      tag: 4.2.1

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    env:
      TZ: "Europe/Berlin"

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: appdaemon-local-path-claim
        mountPath: /conf

    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
