---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
spec:
  interval: 5m
  chart:
    spec:
      chart: appdaemon
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: acockburn/appdaemon
      tag: 4.2.1

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${CLUSTER_LB_APPDAEMON}
        externalTrafficPolicy: Local

    env:
      TZ: "Europe/Berlin"
      HA_URL: http://home-assistant:$(HOME_ASSISTANT_SERVICE_PORT)
      TOKEN:
        secretKeyRef:
          name: appdaemon-secrets
          key: token
      DASH-URL: http://appdaemon:$(APPDAEMON_SERVICE_PORT)
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: appd-rwm-longhorn-pvc
        mountPath: /conf

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.6.0
        service:
          enabled: true
        workingDir: "/conf"
        env:
          GIT_SSH_COMMAND: "ssh -i /conf/.ssh/id_rsa -o IdentitiesOnly=yes"
          GIT_AUTHOR_NAME: ${SECRET_GIT_NAME}
          GIT_AUTHOR_EMAIL: ${SECRET_GIT_MAIL}
          GIT_COMMITTER_NAME: ${SECRET_GIT_NAME}
          GIT_COMMITTER_EMAIL: ${SECRET_GIT_MAIL}
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/conf/.vscode"
          - --extensions-dir
          - "/conf/.vscode"
        volumeMounts:
          - name: config
            mountPath: /conf
