---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: appdaemon-auth-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`appd.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: appdeamon-appdaemon
          port: 5050
      middlewares:
        - name: traefik-forward-auth
          namespace: networking
  tls:
    secretName: "${SECRET_CERTIFICATE_DEFAULT}"
