---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: pihole-chart
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:

    replicaCount: 1

    admin:
      existingSecret: pihole-secrets
      passwordKey: password

    persistentVolumeClaim:
      existingClaim: pihole-rwm-longhorn-pvc

    serviceDns:
      loadBalancerIP: ${CLUSTER_LB_PIHOLE}
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
