---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-rwm-longhorn-pvc
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
