---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "default-cert"
  namespace: default
spec:
  secretName: "default-cert"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
