---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_CERTIFICATE_DEFAULT}"
  namespace: default
spec:
  secretName: "${SECRET_CERTIFICATE_DEFAULT}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "home-automation,storage-system,networking"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "home-automation,storage-system,networking" # Control auto-reflection namespaces
