---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_CERTIFICATE_DEFAULT}"
  namespace: default
spec:
  secretName: "${SECRET_CERTIFICATE_DEFAULT}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
