---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-config-github-runner
  labels:
    app: appd-config-github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appd-config-github-runner
  template:
    metadata:
      labels:
        app: appd-config-github-runner
    spec:
      containers:
        - name: github-runner
          image: myoung34/github-runner:2.320.0
          env:
            - name: RUNNER_NAME
              value: appd-config-runner
            - name: REPO_URL
              value: https://github.com/carsten-bo/appdaemon-config
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner-secrets
                  key: personal-access-token
          volumeMounts:
            - mountPath: /appd-volume
              name: appd-volume

          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "mkdir -p /root/.ssh"]

          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"

      volumes:
        - name: appd-volume
          persistentVolumeClaim:
            claimName: appd-rwm-longhorn-pvc
