---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-config-github-runner
  labels:
    app: appd-config-github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appd-config-github-runner
  template:
    metadata:
      labels:
        app: appd-config-github-runner
    spec:
      containers:
        - name: github-runner
          image: myoung34/github-runner:2.294.0
          # command: ["/bin/bash -c sudo apt-get update && sudo apt-get install -y libatomic1"]
          env:
            - name: RUNNER_NAME
              value: appd-config-runner
            - name: REPO_URL
              value: https://github.com/carsten-bo/appdaemon-config
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner-secrets
                  key: personal-access-token
          volumeMounts:
            - mountPath: /appd-volume
              name: appd-volume

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

      volumes:
        - name: appd-volume
          persistentVolumeClaim:
            claimName: appdaemon-longhorn-pvc
