---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
spec:
  interval: 30m
  url: https://1password.github.io/connect-helm-charts/
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack-charts
spec:
  interval: 30m
  url: https://charts.jetstack.io/
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
spec:
  interval: 30m
  url: https://k8s-at-home.com/charts/
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-charts
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack-charts
spec:
  interval: 30m
  url: https://emberstack.github.io/helm-charts
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn-charts
spec:
  interval: 30m
  url: https://charts.longhorn.io
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-charts
spec:
  interval: 30m
  url: https://charts.rook.io/release
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-dashboard-charts
spec:
  interval: 30m
  url: https://kubernetes.github.io/dashboard
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfd-charts
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: descheduler-charts
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/descheduler/
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
  timeout: 3m
