---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets-manager.yaml
  - home-automation.yaml
  - cert-manager.yaml
  - storage-system.yaml
  - github-runner.yaml
  - metallb-system.yaml
  - persistence.yaml
  - networking.yaml

commonLabels:
  kustomize.toolkit.fluxcd.io/prune: disabled
